# THIS IS A GENERATED FILE. DO NOT EDIT!
# pylint: skip-file
# Copyright 2020 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_report.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api_report.proto',
  package='tensorflow_docs.api_report.schema',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x61pi_report.proto\x12!tensorflow_docs.api_report.schema\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n\rParameterLint\x12!\n\x19num_empty_param_desc_args\x18\x01 \x01(\x02\x12\x18\n\x10num_args_in_code\x18\x02 \x01(\x02\x12!\n\x19num_empty_param_desc_attr\x18\x03 \x01(\x02\x12\x18\n\x10total_attr_param\x18\x04 \x01(\x02\x12\x17\n\x0fnum_args_in_doc\x18\x05 \x01(\x02\";\n\x0f\x44\x65scriptionLint\x12\x11\n\tlen_brief\x18\x01 \x01(\x02\x12\x15\n\rlen_long_desc\x18\x03 \x01(\x02\"F\n\x10UsageExampleLint\x12\x13\n\x0bnum_doctest\x18\x01 \x01(\x02\x12\x1d\n\x15num_untested_examples\x18\x02 \x01(\x02\"%\n\nReturnLint\x12\x17\n\x0freturns_defined\x18\x01 \x01(\x08\"F\n\nRaisesLint\x12\x1a\n\x12num_raises_defined\x18\x01 \x01(\x02\x12\x1c\n\x14total_raises_in_code\x18\x02 \x01(\x02\"\xeb\x03\n\x0f\x41piSymbolMetric\x12\x13\n\x0bsymbol_name\x18\x01 \x01(\t\x12\x42\n\x0bobject_type\x18\x02 \x01(\x0e\x32-.tensorflow_docs.api_report.schema.ObjectType\x12H\n\x0eparameter_lint\x18\x03 \x01(\x0b\x32\x30.tensorflow_docs.api_report.schema.ParameterLint\x12\x45\n\tdesc_lint\x18\x04 \x01(\x0b\x32\x32.tensorflow_docs.api_report.schema.DescriptionLint\x12O\n\x12usage_example_lint\x18\x05 \x01(\x0b\x32\x33.tensorflow_docs.api_report.schema.UsageExampleLint\x12\x42\n\x0breturn_lint\x18\x06 \x01(\x0b\x32-.tensorflow_docs.api_report.schema.ReturnLint\x12\x42\n\x0braises_lint\x18\x07 \x01(\x0b\x32-.tensorflow_docs.api_report.schema.RaisesLint\x12\x15\n\rpackage_group\x18\x08 \x01(\t\"\x93\x01\n\tApiReport\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12I\n\rsymbol_metric\x18\x03 \x03(\x0b\x32\x32.tensorflow_docs.api_report.schema.ApiSymbolMetric*M\n\nObjectType\x12\t\n\x05\x43LASS\x10\x00\x12\n\n\x06METHOD\x10\x01\x12\x0c\n\x08\x46UNCTION\x10\x02\x12\n\n\x06MODULE\x10\x03\x12\x0e\n\nTYPE_ALIAS\x10\x04'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_OBJECTTYPE = _descriptor.EnumDescriptor(
  name='ObjectType',
  full_name='tensorflow_docs.api_report.schema.ObjectType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLASS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='METHOD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FUNCTION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MODULE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TYPE_ALIAS', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1141,
  serialized_end=1218,
)
_sym_db.RegisterEnumDescriptor(_OBJECTTYPE)

ObjectType = enum_type_wrapper.EnumTypeWrapper(_OBJECTTYPE)
CLASS = 0
METHOD = 1
FUNCTION = 2
MODULE = 3
TYPE_ALIAS = 4



_PARAMETERLINT = _descriptor.Descriptor(
  name='ParameterLint',
  full_name='tensorflow_docs.api_report.schema.ParameterLint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_empty_param_desc_args', full_name='tensorflow_docs.api_report.schema.ParameterLint.num_empty_param_desc_args', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_args_in_code', full_name='tensorflow_docs.api_report.schema.ParameterLint.num_args_in_code', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_empty_param_desc_attr', full_name='tensorflow_docs.api_report.schema.ParameterLint.num_empty_param_desc_attr', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_attr_param', full_name='tensorflow_docs.api_report.schema.ParameterLint.total_attr_param', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_args_in_doc', full_name='tensorflow_docs.api_report.schema.ParameterLint.num_args_in_doc', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=251,
)


_DESCRIPTIONLINT = _descriptor.Descriptor(
  name='DescriptionLint',
  full_name='tensorflow_docs.api_report.schema.DescriptionLint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='len_brief', full_name='tensorflow_docs.api_report.schema.DescriptionLint.len_brief', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='len_long_desc', full_name='tensorflow_docs.api_report.schema.DescriptionLint.len_long_desc', index=1,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=312,
)


_USAGEEXAMPLELINT = _descriptor.Descriptor(
  name='UsageExampleLint',
  full_name='tensorflow_docs.api_report.schema.UsageExampleLint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_doctest', full_name='tensorflow_docs.api_report.schema.UsageExampleLint.num_doctest', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_untested_examples', full_name='tensorflow_docs.api_report.schema.UsageExampleLint.num_untested_examples', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=384,
)


_RETURNLINT = _descriptor.Descriptor(
  name='ReturnLint',
  full_name='tensorflow_docs.api_report.schema.ReturnLint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='returns_defined', full_name='tensorflow_docs.api_report.schema.ReturnLint.returns_defined', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=423,
)


_RAISESLINT = _descriptor.Descriptor(
  name='RaisesLint',
  full_name='tensorflow_docs.api_report.schema.RaisesLint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_raises_defined', full_name='tensorflow_docs.api_report.schema.RaisesLint.num_raises_defined', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_raises_in_code', full_name='tensorflow_docs.api_report.schema.RaisesLint.total_raises_in_code', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=495,
)


_APISYMBOLMETRIC = _descriptor.Descriptor(
  name='ApiSymbolMetric',
  full_name='tensorflow_docs.api_report.schema.ApiSymbolMetric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol_name', full_name='tensorflow_docs.api_report.schema.ApiSymbolMetric.symbol_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='object_type', full_name='tensorflow_docs.api_report.schema.ApiSymbolMetric.object_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameter_lint', full_name='tensorflow_docs.api_report.schema.ApiSymbolMetric.parameter_lint', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desc_lint', full_name='tensorflow_docs.api_report.schema.ApiSymbolMetric.desc_lint', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='usage_example_lint', full_name='tensorflow_docs.api_report.schema.ApiSymbolMetric.usage_example_lint', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='return_lint', full_name='tensorflow_docs.api_report.schema.ApiSymbolMetric.return_lint', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raises_lint', full_name='tensorflow_docs.api_report.schema.ApiSymbolMetric.raises_lint', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='package_group', full_name='tensorflow_docs.api_report.schema.ApiSymbolMetric.package_group', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=989,
)


_APIREPORT = _descriptor.Descriptor(
  name='ApiReport',
  full_name='tensorflow_docs.api_report.schema.ApiReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='tensorflow_docs.api_report.schema.ApiReport.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='tensorflow_docs.api_report.schema.ApiReport.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol_metric', full_name='tensorflow_docs.api_report.schema.ApiReport.symbol_metric', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=992,
  serialized_end=1139,
)

_APISYMBOLMETRIC.fields_by_name['object_type'].enum_type = _OBJECTTYPE
_APISYMBOLMETRIC.fields_by_name['parameter_lint'].message_type = _PARAMETERLINT
_APISYMBOLMETRIC.fields_by_name['desc_lint'].message_type = _DESCRIPTIONLINT
_APISYMBOLMETRIC.fields_by_name['usage_example_lint'].message_type = _USAGEEXAMPLELINT
_APISYMBOLMETRIC.fields_by_name['return_lint'].message_type = _RETURNLINT
_APISYMBOLMETRIC.fields_by_name['raises_lint'].message_type = _RAISESLINT
_APIREPORT.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_APIREPORT.fields_by_name['symbol_metric'].message_type = _APISYMBOLMETRIC
DESCRIPTOR.message_types_by_name['ParameterLint'] = _PARAMETERLINT
DESCRIPTOR.message_types_by_name['DescriptionLint'] = _DESCRIPTIONLINT
DESCRIPTOR.message_types_by_name['UsageExampleLint'] = _USAGEEXAMPLELINT
DESCRIPTOR.message_types_by_name['ReturnLint'] = _RETURNLINT
DESCRIPTOR.message_types_by_name['RaisesLint'] = _RAISESLINT
DESCRIPTOR.message_types_by_name['ApiSymbolMetric'] = _APISYMBOLMETRIC
DESCRIPTOR.message_types_by_name['ApiReport'] = _APIREPORT
DESCRIPTOR.enum_types_by_name['ObjectType'] = _OBJECTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParameterLint = _reflection.GeneratedProtocolMessageType('ParameterLint', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERLINT,
  '__module__' : 'api_report_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_docs.api_report.schema.ParameterLint)
  })
_sym_db.RegisterMessage(ParameterLint)

DescriptionLint = _reflection.GeneratedProtocolMessageType('DescriptionLint', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIPTIONLINT,
  '__module__' : 'api_report_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_docs.api_report.schema.DescriptionLint)
  })
_sym_db.RegisterMessage(DescriptionLint)

UsageExampleLint = _reflection.GeneratedProtocolMessageType('UsageExampleLint', (_message.Message,), {
  'DESCRIPTOR' : _USAGEEXAMPLELINT,
  '__module__' : 'api_report_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_docs.api_report.schema.UsageExampleLint)
  })
_sym_db.RegisterMessage(UsageExampleLint)

ReturnLint = _reflection.GeneratedProtocolMessageType('ReturnLint', (_message.Message,), {
  'DESCRIPTOR' : _RETURNLINT,
  '__module__' : 'api_report_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_docs.api_report.schema.ReturnLint)
  })
_sym_db.RegisterMessage(ReturnLint)

RaisesLint = _reflection.GeneratedProtocolMessageType('RaisesLint', (_message.Message,), {
  'DESCRIPTOR' : _RAISESLINT,
  '__module__' : 'api_report_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_docs.api_report.schema.RaisesLint)
  })
_sym_db.RegisterMessage(RaisesLint)

ApiSymbolMetric = _reflection.GeneratedProtocolMessageType('ApiSymbolMetric', (_message.Message,), {
  'DESCRIPTOR' : _APISYMBOLMETRIC,
  '__module__' : 'api_report_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_docs.api_report.schema.ApiSymbolMetric)
  })
_sym_db.RegisterMessage(ApiSymbolMetric)

ApiReport = _reflection.GeneratedProtocolMessageType('ApiReport', (_message.Message,), {
  'DESCRIPTOR' : _APIREPORT,
  '__module__' : 'api_report_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow_docs.api_report.schema.ApiReport)
  })
_sym_db.RegisterMessage(ApiReport)


# @@protoc_insertion_point(module_scope)